USE project_demo_db;

INSERT INTO settings (set_key, set_value) VALUES
('defaultLanguage', 'ar'),
('displayDigits', '3'),
('bulkStatus', '1'),
('audioShortBeep', '0'),
('feedbackUpdated', '0'),
('bigdisplayMessageCount', '5'),
('maxCount', '10'),
('counterSwitchServices', '1'),
('counter_callDelaySeconds', '3'),
('counter_recallTimes', '3'),
('displayType', 'tcp'),
('bulkDelay', '5'),
('maxTransactions', '10'),
('maxBulkNumber', '10'),
('minimumCategoriesCount', '1')
ON DUPLICATE KEY UPDATE set_value = VALUES(set_value);

INSERT INTO zones (zone_id, zone_name, zone_desc) VALUES
(1, 'Main Hall', 'Demo main service hall')
ON DUPLICATE KEY UPDATE zone_name = VALUES(zone_name), zone_desc = VALUES(zone_desc);

INSERT INTO bigdisplaytypes (bdtype_id, bdtype_name) VALUES
(1, 'Latest Call'),
(2, 'Bulk Waiting'),
(3, 'Counter Calls'),
(4, 'Latest With Waiting')
ON DUPLICATE KEY UPDATE bdtype_name = VALUES(bdtype_name);

INSERT INTO users (user_name, user_password, user_privileges, user_fullname, user_desc, user_phone) VALUES
('admin.demo@example.com', SHA2('AdminDemo@123', 256), 255, 'Demo Admin', 'Full demo administrator', '0500000001'),
('viewer.demo@example.com', SHA2('ViewerDemo@123', 256), 65, 'Demo Viewer', 'Read/report demo user', '0500000003')
ON DUPLICATE KEY UPDATE user_password = VALUES(user_password), user_privileges = VALUES(user_privileges), user_fullname = VALUES(user_fullname);

INSERT INTO clerks (clerk_name, clerk_password, clerk_fullname, clerk_desc, clerk_phone, clerk_zone) VALUES
('operator.demo@example.com', SHA2('OperatorDemo@123', 256), 'Demo Operator', 'Counter operator for demo testing', '0500000002', 1)
ON DUPLICATE KEY UPDATE clerk_password = VALUES(clerk_password), clerk_fullname = VALUES(clerk_fullname), clerk_zone = VALUES(clerk_zone);

INSERT INTO texts (text_language, text_key, text_value) VALUES
('ar', 'dir', 'rtl'),
('en', 'dir', 'ltr'),
('ar', 'CAT001', 'خدمة العملاء'),
('en', 'CAT001', 'Customer Service'),
('ar', 'CAT002', 'المعاملات المالية'),
('en', 'CAT002', 'Payments'),
('ar', 'adminLogin', 'تسجيل دخول الإدارة'),
('en', 'adminLogin', 'Admin Login'),
('ar', 'userPrivileges1', 'التقارير والعمليات'),
('ar', 'userPrivileges2', 'إدارة الموظفين'),
('ar', 'userPrivileges4', 'صلاحية احتياطية'),
('ar', 'userPrivileges8', 'الدخول العام'),
('ar', 'userPrivileges16', 'إعدادات النظام'),
('ar', 'userPrivileges32', 'إدارة المستخدمين'),
('ar', 'userPrivileges64', 'البحث'),
('ar', 'userPrivileges128', 'اللغات')
ON DUPLICATE KEY UPDATE text_value = VALUES(text_value);

-- Full UI translation set (all getTextValue() keys used across the app)
INSERT INTO texts (text_language, text_key, text_value) VALUES
('ar', 'active', 'نشط'),
('en', 'active', 'Active'),
('ar', 'add', 'إضافة'),
('en', 'add', 'Add'),
('ar', 'addEditAudios', 'إضافة/تعديل صوت'),
('en', 'addEditAudios', 'Add/Edit Audio'),
('ar', 'addEditBigDisplayBulk', 'إضافة/تعديل عنصر العرض الجماعي'),
('en', 'addEditBigDisplayBulk', 'Add/Edit Bulk Display Item'),
('ar', 'addEditBigDisplayCounters', 'إضافة/تعديل طاولات الشاشة الكبيرة'),
('en', 'addEditBigDisplayCounters', 'Add/Edit Big Display Counters'),
('ar', 'addEditBigDisplayForCounter', 'إضافة/تعديل الشاشة الكبيرة للطاولة'),
('en', 'addEditBigDisplayForCounter', 'Add/Edit Big Display for Counter'),
('ar', 'addEditBigDisplays', 'إضافة/تعديل شاشة كبيرة'),
('en', 'addEditBigDisplays', 'Add/Edit Big Display'),
('ar', 'addEditCategories', 'إضافة/تعديل فئة'),
('en', 'addEditCategories', 'Add/Edit Category'),
('ar', 'addEditClerks', 'إضافة/تعديل موظف'),
('en', 'addEditClerks', 'Add/Edit Clerk'),
('ar', 'addEditCounterCategories', 'إضافة/تعديل فئات الطاولة'),
('en', 'addEditCounterCategories', 'Add/Edit Counter Categories'),
('ar', 'addEditCounters', 'إضافة/تعديل طاولة'),
('en', 'addEditCounters', 'Add/Edit Counter'),
('ar', 'addEditDisplays', 'إضافة/تعديل شاشة'),
('en', 'addEditDisplays', 'Add/Edit Display'),
('ar', 'addEditExtensionNumbers', 'إضافة/تعديل رقم تحويلة'),
('en', 'addEditExtensionNumbers', 'Add/Edit Extension Number'),
('ar', 'addEditKioskButtons', 'إضافة/تعديل زر الكشك'),
('en', 'addEditKioskButtons', 'Add/Edit Kiosk Button'),
('ar', 'addEditKiosks', 'إضافة/تعديل كشك'),
('en', 'addEditKiosks', 'Add/Edit Kiosk'),
('ar', 'addEditUsers', 'إضافة/تعديل مستخدم'),
('en', 'addEditUsers', 'Add/Edit User'),
('ar', 'addEditZone', 'إضافة/تعديل منطقة'),
('en', 'addEditZone', 'Add/Edit Zone'),
('ar', 'addPending', 'إضافة إلى قائمة الانتظار'),
('en', 'addPending', 'Add to pending'),
('ar', 'adminOnly', 'الإدارة فقط'),
('en', 'adminOnly', 'Admin only'),
('ar', 'advancedSearch', 'بحث متقدم'),
('en', 'advancedSearch', 'Advanced search'),
('ar', 'allCategories', 'كل الفئات'),
('en', 'allCategories', 'All categories'),
('ar', 'allSystem', 'النظام بالكامل'),
('en', 'allSystem', 'Whole system'),
('ar', 'areYouSure', 'هل أنت متأكد؟'),
('en', 'areYouSure', 'Are you sure?'),
('ar', 'arrowDir', 'rtl'),
('en', 'arrowDir', 'ltr'),
('ar', 'audioLanguage', 'لغة الصوت'),
('en', 'audioLanguage', 'Audio language'),
('ar', 'audioName', 'اسم الصوت'),
('en', 'audioName', 'Audio name'),
('ar', 'audioPath', 'ملف الصوت'),
('en', 'audioPath', 'Audio file'),
('ar', 'audios', 'الأصوات'),
('en', 'audios', 'Audios'),
('ar', 'autocall', 'نداء تلقائي'),
('en', 'autocall', 'Auto call'),
('ar', 'autoLogin', 'دخول تلقائي'),
('en', 'autoLogin', 'Auto login'),
('ar', 'avarage', 'المعدل'),
('en', 'avarage', 'Average'),
('ar', 'avarageOfFinished', 'معدل المنتهية'),
('en', 'avarageOfFinished', 'Average of finished'),
('ar', 'back', 'رجوع'),
('en', 'back', 'Back'),
('ar', 'backToQueueSuccess', 'تمت الإعادة إلى قائمة الانتظار بنجاح'),
('en', 'backToQueueSuccess', 'Returned to queue successfully'),
('ar', 'bigDisplay', 'الشاشة الكبيرة'),
('en', 'bigDisplay', 'Big display'),
('ar', 'bigDisplayBulk', 'عرض جماعي للشاشة الكبيرة'),
('en', 'bigDisplayBulk', 'Big display bulk'),
('ar', 'bigDisplayCounters', 'طاولات الشاشة الكبيرة'),
('en', 'bigDisplayCounters', 'Big display counters'),
('ar', 'bigdisplayForCounter', 'الشاشة الكبيرة للطاولة'),
('en', 'bigdisplayForCounter', 'Big display for counter'),
('ar', 'bigDisplayName', 'اسم الشاشة الكبيرة'),
('en', 'bigDisplayName', 'Big display name'),
('ar', 'bigDisplayNo', 'رقم الشاشة الكبيرة'),
('en', 'bigDisplayNo', 'Big display no.'),
('ar', 'bigdisplays', 'الشاشات الكبيرة'),
('en', 'bigdisplays', 'Big displays'),
('ar', 'bigDisplayZone', 'منطقة الشاشة الكبيرة'),
('en', 'bigDisplayZone', 'Big display zone'),
('ar', 'bulk', 'جماعي'),
('en', 'bulk', 'Bulk'),
('ar', 'call', 'نداء'),
('en', 'call', 'Call'),
('ar', 'callingDelay', 'تأخير النداء'),
('en', 'callingDelay', 'Calling delay'),
('ar', 'cancel', 'إلغاء'),
('en', 'cancel', 'Cancel'),
('ar', 'canPickTickets', 'يمكنه سحب التذاكر'),
('en', 'canPickTickets', 'Can pick tickets'),
('ar', 'categories', 'الفئات'),
('en', 'categories', 'Categories'),
('ar', 'categoriesCount', 'عدد الفئات'),
('en', 'categoriesCount', 'Categories count'),
('ar', 'category', 'الفئة'),
('en', 'category', 'Category'),
('ar', 'categoryChar', 'حرف الفئة'),
('en', 'categoryChar', 'Category letter'),
('ar', 'categoryEnabled', 'الفئة مفعّلة'),
('en', 'categoryEnabled', 'Category enabled'),
('ar', 'categoryKey', 'مفتاح الفئة'),
('en', 'categoryKey', 'Category key'),
('ar', 'categoryParent', 'الفئة الأصل'),
('en', 'categoryParent', 'Parent category'),
('ar', 'categoryZone', 'منطقة الفئة'),
('en', 'categoryZone', 'Category zone'),
('ar', 'choosepriority', 'اختر الأولوية'),
('en', 'choosepriority', 'Choose priority'),
('ar', 'clear', 'مسح'),
('en', 'clear', 'Clear'),
('ar', 'clerkCounter', 'طاولة الموظف'),
('en', 'clerkCounter', 'Clerk counter'),
('ar', 'clerkDesc', 'وصف الموظف'),
('en', 'clerkDesc', 'Clerk description'),
('ar', 'clerkFullName', 'الاسم الكامل للموظف'),
('en', 'clerkFullName', 'Clerk full name'),
('ar', 'clerkLogin', 'دخول الموظف'),
('en', 'clerkLogin', 'Clerk login'),
('ar', 'clerkName', 'اسم الموظف'),
('en', 'clerkName', 'Clerk name'),
('ar', 'clerkPassword', 'كلمة مرور الموظف'),
('en', 'clerkPassword', 'Clerk password'),
('ar', 'clerks', 'الموظفون'),
('en', 'clerks', 'Clerks'),
('ar', 'clerksNo', 'عدد الموظفين'),
('en', 'clerksNo', 'Clerks no.'),
('ar', 'clerkZone', 'منطقة الموظف'),
('en', 'clerkZone', 'Clerk zone'),
('ar', 'clientInfo', 'معلومات العميل'),
('en', 'clientInfo', 'Client info'),
('ar', 'clientName', 'اسم العميل'),
('en', 'clientName', 'Client name'),
('ar', 'clock', 'الساعة'),
('en', 'clock', 'Clock'),
('ar', 'close', 'إغلاق'),
('en', 'close', 'Close'),
('ar', 'closeCounter', 'إغلاق الطاولة'),
('en', 'closeCounter', 'Close counter'),
('ar', 'closed', 'مغلق'),
('en', 'closed', 'Closed'),
('ar', 'counter', 'الطاولة'),
('en', 'counter', 'Counter'),
('ar', 'counterAudio', 'صوت الطاولة'),
('en', 'counterAudio', 'Counter audio'),
('ar', 'counterDisplay', 'شاشة الطاولة'),
('en', 'counterDisplay', 'Counter display'),
('ar', 'counterLoad', 'حِمل الطاولة'),
('en', 'counterLoad', 'Counter load'),
('ar', 'counterName', 'اسم الطاولة'),
('en', 'counterName', 'Counter name'),
('ar', 'counterNo', 'رقم الطاولة'),
('en', 'counterNo', 'Counter no.'),
('ar', 'counters', 'الطاولات'),
('en', 'counters', 'Counters'),
('ar', 'counterscategories', 'فئات الطاولات'),
('en', 'counterscategories', 'Counter categories'),
('ar', 'countersCategories', 'فئات الطاولات'),
('en', 'countersCategories', 'Counter categories'),
('ar', 'countersNo', 'عدد الطاولات'),
('en', 'countersNo', 'Counters no.'),
('ar', 'counterZone', 'منطقة الطاولة'),
('en', 'counterZone', 'Counter zone'),
('ar', 'counts', 'الأعداد'),
('en', 'counts', 'Counts'),
('ar', 'created', 'تاريخ الإنشاء'),
('en', 'created', 'Created'),
('ar', 'dateTime', 'التاريخ والوقت'),
('en', 'dateTime', 'Date/time'),
('ar', 'days', 'أيام'),
('en', 'days', 'Days'),
('ar', 'delete', 'حذف'),
('en', 'delete', 'Delete'),
('ar', 'deleteQuestion', 'حذف هذا العنصر'),
('en', 'deleteQuestion', 'Delete this item'),
('ar', 'details', 'التفاصيل'),
('en', 'details', 'Details'),
('ar', 'directorate', 'المديرية'),
('en', 'directorate', 'Directorate'),
('ar', 'directTransfer', 'تحويل مباشر'),
('en', 'directTransfer', 'Direct transfer'),
('ar', 'directTransferCategory', 'فئة التحويل المباشر'),
('en', 'directTransferCategory', 'Direct transfer category'),
('ar', 'displayName', 'اسم الشاشة'),
('en', 'displayName', 'Display name'),
('ar', 'displays', 'الشاشات'),
('en', 'displays', 'Displays'),
('ar', 'displaysNo', 'عدد الشاشات'),
('en', 'displaysNo', 'Displays no.'),
('ar', 'displayZone', 'منطقة الشاشة'),
('en', 'displayZone', 'Display zone'),
('ar', 'distCategory', 'الفئة'),
('en', 'distCategory', 'Category'),
('ar', 'distCounter', 'الطاولة'),
('en', 'distCounter', 'Counter'),
('ar', 'doesnotexit', 'غير موجود'),
('en', 'doesnotexit', 'does not exist'),
('ar', 'edit', 'تعديل'),
('en', 'edit', 'Edit'),
('ar', 'effeciencySpeed', 'سرعة الأداء'),
('en', 'effeciencySpeed', 'Efficiency speed'),
('ar', 'empty', 'فارغ'),
('en', 'empty', 'Empty'),
('ar', 'enter', 'دخول'),
('en', 'enter', 'Enter'),
('ar', 'enterNewLanguage', 'أدخل لغة جديدة'),
('en', 'enterNewLanguage', 'Enter new language'),
('ar', 'enterTime', 'وقت الدخول'),
('en', 'enterTime', 'Enter time'),
('ar', 'errorBulkNumber', 'رقم جماعي غير صالح'),
('en', 'errorBulkNumber', 'Invalid bulk number'),
('ar', 'errorClose', 'فشل الإغلاق'),
('en', 'errorClose', 'Failed to close'),
('ar', 'errorCounterDoesntExist', 'الطاولة غير موجودة'),
('en', 'errorCounterDoesntExist', 'Counter does not exist'),
('ar', 'errorDelete', 'فشل الحذف'),
('en', 'errorDelete', 'Failed to delete'),
('ar', 'errorFromToDate', 'نطاق تاريخ غير صالح'),
('en', 'errorFromToDate', 'Invalid date range'),
('ar', 'errorInOperation', 'فشلت العملية'),
('en', 'errorInOperation', 'Operation failed'),
('ar', 'errorInPendingState', 'العنصر في حالة انتظار'),
('en', 'errorInPendingState', 'Item is in pending state'),
('ar', 'errorLogin', 'فشل تسجيل الدخول'),
('en', 'errorLogin', 'Login failed'),
('ar', 'errorLogout', 'فشل تسجيل الخروج'),
('en', 'errorLogout', 'Logout failed'),
('ar', 'errorNumber', 'رقم غير صالح'),
('en', 'errorNumber', 'Invalid number'),
('ar', 'errorPrioritySet', 'فشل تعيين الأولوية'),
('en', 'errorPrioritySet', 'Failed to set priority'),
('ar', 'errorTransfer', 'فشل التحويل'),
('en', 'errorTransfer', 'Transfer failed'),
('ar', 'errorUpdate', 'فشل التحديث'),
('en', 'errorUpdate', 'Update failed'),
('ar', 'eventNo', 'رقم التذكرة'),
('en', 'eventNo', 'Ticket no.'),
('ar', 'eventPriority', 'الأولوية'),
('en', 'eventPriority', 'Priority'),
('ar', 'eventsClosed', 'التذاكر المغلقة'),
('en', 'eventsClosed', 'Closed tickets'),
('ar', 'eventsNo', 'عدد التذاكر'),
('en', 'eventsNo', 'Tickets no.'),
('ar', 'eventsTransferred', 'التذاكر المحوّلة'),
('en', 'eventsTransferred', 'Transferred tickets'),
('ar', 'eventsWaiting', 'التذاكر المنتظرة'),
('en', 'eventsWaiting', 'Waiting tickets'),
('ar', 'excelExport', 'تصدير إلى إكسل'),
('en', 'excelExport', 'Export to Excel'),
('ar', 'extensionNumbers', 'أرقام التحويلات'),
('en', 'extensionNumbers', 'Extension numbers'),
('ar', 'feedbackOpinion', 'قيّم تجربتك'),
('en', 'feedbackOpinion', 'Rate your experience'),
('ar', 'feedbackQuestion', 'سؤال التقييم'),
('en', 'feedbackQuestion', 'Feedback question'),
('ar', 'feedbackQuestionTxt', 'نص السؤال'),
('en', 'feedbackQuestionTxt', 'Question text'),
('ar', 'feedbacks', 'التقييمات'),
('en', 'feedbacks', 'Feedback'),
('ar', 'fileList', 'قائمة الملفات'),
('en', 'fileList', 'File list'),
('ar', 'fileName', 'اسم الملف'),
('en', 'fileName', 'File name'),
('ar', 'fileSize', 'حجم الملف'),
('en', 'fileSize', 'File size'),
('ar', 'finalScore', 'النتيجة النهائية'),
('en', 'finalScore', 'Final score'),
('ar', 'finished', 'منتهية'),
('en', 'finished', 'Finished'),
('ar', 'firstPage', 'الصفحة الأولى'),
('en', 'firstPage', 'First page'),
('ar', 'flow', 'التدفق'),
('en', 'flow', 'Flow'),
('ar', 'followupCard', 'بطاقة متابعة'),
('en', 'followupCard', 'Follow-up card'),
('ar', 'followupCards', 'بطاقات المتابعة'),
('en', 'followupCards', 'Follow-up cards'),
('ar', 'followupFootnote1', 'يرجى الاحتفاظ بهذه البطاقة حتى دوركم'),
('en', 'followupFootnote1', 'Please keep this card until your turn'),
('ar', 'followupFootnote2', 'تابعوا رقمكم على شاشة العرض'),
('en', 'followupFootnote2', 'Watch the display screen for your number'),
('ar', 'followupFootnote3', 'شكراً لصبركم'),
('en', 'followupFootnote3', 'Thank you for your patience'),
('ar', 'followupFootnote4', 'للاستفسار يرجى التواصل مع الاستقبال'),
('en', 'followupFootnote4', 'For inquiries, contact reception'),
('ar', 'followupFootnote5', 'نظام إدارة الطوابير iDEAL-Q'),
('en', 'followupFootnote5', 'iDEAL-Q Queue Management System'),
('ar', 'from', 'من'),
('en', 'from', 'From'),
('ar', 'gender', 'الجنس'),
('en', 'gender', 'Gender'),
('ar', 'generalInfo', 'معلومات عامة'),
('en', 'generalInfo', 'General info'),
('ar', 'getticketinfo', 'استعلام عن التذكرة'),
('en', 'getticketinfo', 'Get ticket info'),
('ar', 'goToHall', 'التوجه إلى القاعة'),
('en', 'goToHall', 'Go to hall'),
('ar', 'gotoPlace', 'التوجه إلى'),
('en', 'gotoPlace', 'Go to'),
('ar', 'group', 'المجموعة'),
('en', 'group', 'Group'),
('ar', 'happy', 'راضٍ'),
('en', 'happy', 'Happy'),
('ar', 'hasbeencalledby', 'تم نداؤها من قِبل'),
('en', 'hasbeencalledby', 'has been called by'),
('ar', 'hello', 'مرحباً'),
('en', 'hello', 'Hello'),
('ar', 'inactive', 'غير نشط'),
('en', 'inactive', 'Inactive'),
('ar', 'inputteckitnumber', 'أدخل رقم التذكرة'),
('en', 'inputteckitnumber', 'Enter ticket number'),
('ar', 'insertSuccessfully', 'تمت الإضافة بنجاح'),
('en', 'insertSuccessfully', 'Added successfully'),
('ar', 'insideReport', 'التقرير'),
('en', 'insideReport', 'Report'),
('ar', 'interface', 'الواجهة'),
('en', 'interface', 'Interface'),
('ar', 'issue', 'إصدار'),
('en', 'issue', 'Issue'),
('ar', 'issueFollowupCard', 'إصدار بطاقة متابعة'),
('en', 'issueFollowupCard', 'Issue follow-up card'),
('ar', 'issuingCards', 'إصدار البطاقات'),
('en', 'issuingCards', 'Issuing cards'),
('ar', 'kbCategory', 'فئة الزر'),
('en', 'kbCategory', 'Button category'),
('ar', 'kbKiosk', 'كشك الزر'),
('en', 'kbKiosk', 'Button kiosk'),
('ar', 'kbPriority', 'أولوية الزر'),
('en', 'kbPriority', 'Button priority'),
('ar', 'kioskbuttons', 'أزرار الكشك'),
('en', 'kioskbuttons', 'Kiosk buttons'),
('ar', 'kioskButtons', 'أزرار الكشك'),
('en', 'kioskButtons', 'Kiosk buttons'),
('ar', 'kioskName', 'اسم الكشك'),
('en', 'kioskName', 'Kiosk name'),
('ar', 'kioskPrinterLocation', 'موقع الطابعة'),
('en', 'kioskPrinterLocation', 'Printer location'),
('ar', 'kioskPrinterParam', 'إعدادات الطابعة'),
('en', 'kioskPrinterParam', 'Printer parameters'),
('ar', 'kioskPrinterType', 'نوع الطابعة'),
('en', 'kioskPrinterType', 'Printer type'),
('ar', 'kiosks', 'الأكشاك'),
('en', 'kiosks', 'Kiosks'),
('ar', 'kiosksNo', 'عدد الأكشاك'),
('en', 'kiosksNo', 'Kiosks no.'),
('ar', 'kioskZone', 'منطقة الكشك'),
('en', 'kioskZone', 'Kiosk zone'),
('ar', 'languageName', 'اللغة'),
('en', 'languageName', 'Language'),
('ar', 'languages', 'اللغات'),
('en', 'languages', 'Languages'),
('ar', 'lastCalled', 'آخر نداء'),
('en', 'lastCalled', 'Last called'),
('ar', 'lastPage', 'الصفحة الأخيرة'),
('en', 'lastPage', 'Last page'),
('ar', 'lastSeen', 'آخر ظهور'),
('en', 'lastSeen', 'Last seen'),
('ar', 'latest', 'الأحدث'),
('en', 'latest', 'Latest'),
('ar', 'lessWaittime', 'وقت انتظار أقل'),
('en', 'lessWaittime', 'Less waiting time'),
('ar', 'login', 'تسجيل الدخول'),
('en', 'login', 'Login'),
('ar', 'logout', 'تسجيل الخروج'),
('en', 'logout', 'Logout'),
('ar', 'logoutMessage', 'تم تسجيل خروجك'),
('en', 'logoutMessage', 'You have been logged out'),
('ar', 'mainPage', 'الصفحة الرئيسية'),
('en', 'mainPage', 'Main page'),
('ar', 'mainService', 'الخدمة الرئيسية'),
('en', 'mainService', 'Main service'),
('ar', 'markProcessed', 'تحديد كمعالَجة'),
('en', 'markProcessed', 'Mark as processed'),
('ar', 'message', 'رسالة'),
('en', 'message', 'Message'),
('ar', 'messages', 'الرسائل'),
('en', 'messages', 'Messages'),
('ar', 'minutes', 'دقائق'),
('en', 'minutes', 'Minutes'),
('ar', 'morepapers', 'المستندات المطلوبة'),
('en', 'morepapers', 'Required documents'),
('ar', 'moreWaittime', 'وقت انتظار أكثر'),
('en', 'moreWaittime', 'More waiting time'),
('ar', 'name', 'الاسم'),
('en', 'name', 'Name'),
('ar', 'newpriority', 'أولوية جديدة'),
('en', 'newpriority', 'New priority'),
('ar', 'no', 'لا'),
('en', 'no', 'No'),
('ar', 'noClients', 'لا يوجد عملاء'),
('en', 'noClients', 'No clients'),
('ar', 'noPriority', 'بدون أولوية'),
('en', 'noPriority', 'No priority'),
('ar', 'notcalledyet', 'لم يُنادَ بعد'),
('en', 'notcalledyet', 'Not called yet'),
('ar', 'notImportant', 'غير مهم'),
('en', 'notImportant', 'Not important'),
('ar', 'notProcessed', 'لم تتم معالجتها'),
('en', 'notProcessed', 'Not processed'),
('ar', 'notReady', 'غير جاهز'),
('en', 'notReady', 'Not ready'),
('ar', 'number', 'الرقم'),
('en', 'number', 'Number'),
('ar', 'numberoftickets', 'عدد التذاكر'),
('en', 'numberoftickets', 'Number of tickets'),
('ar', 'numberOftickets', 'عدد التذاكر'),
('en', 'numberOftickets', 'Number of tickets'),
('ar', 'ok', 'موافق'),
('en', 'ok', 'OK'),
('ar', 'open', 'فتح'),
('en', 'open', 'Open'),
('ar', 'opened', 'مفتوح'),
('en', 'opened', 'Opened'),
('ar', 'password', 'كلمة المرور'),
('en', 'password', 'Password'),
('ar', 'pendingList', 'قائمة الانتظار المؤجل'),
('en', 'pendingList', 'Pending list'),
('ar', 'phoneNumber', 'رقم الهاتف'),
('en', 'phoneNumber', 'Phone number'),
('ar', 'pleaseCall', 'يرجى النداء'),
('en', 'pleaseCall', 'Please call'),
('ar', 'pleaseRateAllQuestions', 'يرجى تقييم جميع الأسئلة'),
('en', 'pleaseRateAllQuestions', 'Please rate all questions'),
('ar', 'print', 'طباعة'),
('en', 'print', 'Print'),
('ar', 'printerParameters', 'إعدادات الطابعة'),
('en', 'printerParameters', 'Printer parameters'),
('ar', 'priority', 'الأولوية'),
('en', 'priority', 'Priority'),
('ar', 'prioritysummary', 'ملخص الأولوية'),
('en', 'prioritysummary', 'Priority summary'),
('ar', 'processed', 'تمت معالجتها'),
('en', 'processed', 'Processed'),
('ar', 'quantity', 'الكمية'),
('en', 'quantity', 'Quantity'),
('ar', 'questionMark', '؟'),
('en', 'questionMark', '?'),
('ar', 'ready', 'جاهز'),
('en', 'ready', 'Ready'),
('ar', 'recall', 'إعادة نداء'),
('en', 'recall', 'Recall'),
('ar', 'recallAll', 'إعادة نداء الكل'),
('en', 'recallAll', 'Recall all'),
('ar', 'reports', 'التقارير'),
('en', 'reports', 'Reports'),
('ar', 'requiredPapers', 'المستندات المطلوبة'),
('en', 'requiredPapers', 'Required documents'),
('ar', 'returnToQueue', 'إعادة إلى قائمة الانتظار'),
('en', 'returnToQueue', 'Return to queue'),
('ar', 'satisfactionScore', 'درجة الرضا'),
('en', 'satisfactionScore', 'Satisfaction score'),
('ar', 'save', 'حفظ'),
('en', 'save', 'Save'),
('ar', 'search', 'بحث'),
('en', 'search', 'Search'),
('ar', 'searchOptions', 'خيارات البحث'),
('en', 'searchOptions', 'Search options'),
('ar', 'selectDates', 'اختر التواريخ'),
('en', 'selectDates', 'Select dates'),
('ar', 'selectLanguage', 'اختر اللغة'),
('en', 'selectLanguage', 'Select language'),
('ar', 'serialNo', 'الرقم التسلسلي'),
('en', 'serialNo', 'Serial no.'),
('ar', 'serialNoRef', 'مرجع الرقم التسلسلي'),
('en', 'serialNoRef', 'Serial no. reference'),
('ar', 'servedCategory', 'الفئة المخدومة'),
('en', 'servedCategory', 'Served category'),
('ar', 'serviceType', 'نوع الخدمة'),
('en', 'serviceType', 'Service type'),
('ar', 'setDefaultLanguage', 'تعيين اللغة الافتراضية'),
('en', 'setDefaultLanguage', 'Set default language'),
('ar', 'setpriority', 'تعيين الأولوية'),
('en', 'setpriority', 'Set priority'),
('ar', 'smsSent', 'تم إرسال الرسالة النصية'),
('en', 'smsSent', 'SMS sent'),
('ar', 'startBulkCalling', 'بدء النداء الجماعي'),
('en', 'startBulkCalling', 'Start bulk calling'),
('ar', 'state', 'الحالة'),
('en', 'state', 'State'),
('ar', 'stopBulkCalling', 'إيقاف النداء الجماعي'),
('en', 'stopBulkCalling', 'Stop bulk calling'),
('ar', 'subcategories', 'الفئات الفرعية'),
('en', 'subcategories', 'Subcategories'),
('ar', 'subFone', 'هاتف فرعي'),
('en', 'subFone', 'Sub phone'),
('ar', 'submit', 'إرسال'),
('en', 'submit', 'Submit'),
('ar', 'subService', 'خدمة فرعية'),
('en', 'subService', 'Sub-service'),
('ar', 'textAlign', 'محاذاة النص'),
('en', 'textAlign', 'Text align'),
('ar', 'thanks', 'شكراً لكم'),
('en', 'thanks', 'Thank you'),
('ar', 'ticket', 'التذكرة'),
('en', 'ticket', 'Ticket'),
('ar', 'ticketformaterror', 'صيغة التذكرة غير صحيحة'),
('en', 'ticketformaterror', 'Invalid ticket format'),
('ar', 'ticketprinting', 'طباعة التذاكر'),
('en', 'ticketprinting', 'Ticket printing'),
('ar', 'tickets', 'التذاكر'),
('en', 'tickets', 'Tickets'),
('ar', 'ticketsNO', 'رقم التذكرة'),
('en', 'ticketsNO', 'Ticket no.'),
('ar', 'ticktsForService', 'تذاكر الخدمة'),
('en', 'ticktsForService', 'Tickets for service'),
('ar', 'time', 'الوقت'),
('en', 'time', 'Time'),
('ar', 'times', 'الأوقات'),
('en', 'times', 'Times'),
('ar', 'to', 'إلى'),
('en', 'to', 'To'),
('ar', 'toCategory', 'إلى الفئة'),
('en', 'toCategory', 'To category'),
('ar', 'toCounter', 'إلى الطاولة'),
('en', 'toCounter', 'To counter'),
('ar', 'total', 'الإجمالي'),
('en', 'total', 'Total'),
('ar', 'totalProcessTime', 'إجمالي وقت المعالجة'),
('en', 'totalProcessTime', 'Total process time'),
('ar', 'totalupdatedtickets', 'إجمالي التذاكر المحدَّثة'),
('en', 'totalupdatedtickets', 'Total updated tickets'),
('ar', 'transfer', 'تحويل'),
('en', 'transfer', 'Transfer'),
('ar', 'transferClient', 'تحويل العميل'),
('en', 'transferClient', 'Transfer client'),
('ar', 'transferDone', 'تم التحويل بنجاح'),
('en', 'transferDone', 'Transferred successfully'),
('ar', 'transferred', 'تم تحويلها'),
('en', 'transferred', 'Transferred'),
('ar', 'type', 'النوع'),
('en', 'type', 'Type'),
('ar', 'unhappy', 'غير راضٍ'),
('en', 'unhappy', 'Unhappy'),
('ar', 'update', 'تحديث'),
('en', 'update', 'Update'),
('ar', 'updated', 'تم التحديث'),
('en', 'updated', 'Updated'),
('ar', 'updateTimes', 'أوقات التحديث'),
('en', 'updateTimes', 'Update times'),
('ar', 'upload', 'رفع'),
('en', 'upload', 'Upload'),
('ar', 'userDesc', 'وصف المستخدم'),
('en', 'userDesc', 'User description'),
('ar', 'userFullName', 'الاسم الكامل للمستخدم'),
('en', 'userFullName', 'User full name'),
('ar', 'userName', 'اسم المستخدم'),
('en', 'userName', 'User name'),
('ar', 'userPassword', 'كلمة مرور المستخدم'),
('en', 'userPassword', 'User password'),
('ar', 'userPrivileges', 'صلاحيات المستخدم'),
('en', 'userPrivileges', 'User privileges'),
('ar', 'users', 'المستخدمون'),
('en', 'users', 'Users'),
('ar', 'useSimpleNotification', 'استخدام إشعار مبسط'),
('en', 'useSimpleNotification', 'Use simple notification'),
('ar', 'waitTime', 'وقت الانتظار'),
('en', 'waitTime', 'Wait time'),
('ar', 'wasgivenapriorityof', 'أُعطيت أولوية'),
('en', 'wasgivenapriorityof', 'was given a priority of'),
('ar', 'words', 'الكلمات'),
('en', 'words', 'Words'),
('ar', 'wrongformat', 'صيغة غير صحيحة'),
('en', 'wrongformat', 'Wrong format'),
('ar', 'yes', 'نعم'),
('en', 'yes', 'Yes'),
('ar', 'yourRating', 'تقييمك'),
('en', 'yourRating', 'Your rating'),
('ar', 'zoneDesc', 'وصف المنطقة'),
('en', 'zoneDesc', 'Zone description'),
('ar', 'zoneName', 'اسم المنطقة'),
('en', 'zoneName', 'Zone name'),
('ar', 'zones', 'المناطق'),
('en', 'zones', 'Zones'),
('ar', 'zonesNo', 'عدد المناطق'),
('en', 'zonesNo', 'Zones no.')
ON DUPLICATE KEY UPDATE text_value = VALUES(text_value);

INSERT INTO texts (text_language, text_key, text_value) VALUES
('ar', 'fb0', 'وقت الانتظار'),
('en', 'fb0', 'Waiting time'),
('ar', 'fb1', 'تعامل الموظف'),
('en', 'fb1', 'Staff courtesy'),
('ar', 'fb2', 'جودة الخدمة'),
('en', 'fb2', 'Service quality'),
('ar', 'fb3', 'نظافة المكان'),
('en', 'fb3', 'Facility cleanliness'),
('ar', 'fb4', 'التجربة العامة'),
('en', 'fb4', 'Overall experience')
ON DUPLICATE KEY UPDATE text_value = VALUES(text_value);

INSERT INTO audios (audio_id, audio_name, audio_path, audio_language, audio_gender) VALUES
(1, 'Default Arabic Male', 'files/audios/default.mp3', 'ar', 2)
ON DUPLICATE KEY UPDATE audio_name = VALUES(audio_name), audio_path = VALUES(audio_path);

INSERT INTO displays (display_id, display_name, display_zone, display_updated) VALUES
(1, 'Main Counter Display', 1, 0)
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name), display_zone = VALUES(display_zone);

INSERT INTO bigdisplays (display_id, display_number, display_name, display_zone, display_updated, display_type, goto, arrow_dir) VALUES
(1, 1, 'Main Hall Big Display', 1, 0, 4, 'Counter', 0)
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name), display_zone = VALUES(display_zone), display_type = VALUES(display_type);

INSERT INTO categories (category_id, category_key, serial_no_ref, category_char, category_parent, category_zone, category_enabled) VALUES
(1, 'CAT001', 'A', 'A', 0, 1, 1),
(2, 'CAT002', 'B', 'B', 0, 1, 1)
ON DUPLICATE KEY UPDATE category_key = VALUES(category_key), category_enabled = VALUES(category_enabled);

INSERT INTO subcategories (subcategory_id, subcategory_name, wait_time_days, papers, main_category_id, in_report) VALUES
(1, 'تحديث بيانات العميل', 2, 'هوية وطنية; نموذج طلب', 1, 1),
(2, 'دفع فاتورة', 0, 'رقم الحساب', 2, 1)
ON DUPLICATE KEY UPDATE subcategory_name = VALUES(subcategory_name), main_category_id = VALUES(main_category_id);

INSERT INTO counters (counter_id, counter_name, counter_no, counter_display, counter_audio, counter_zone, counter_active, current_clerk, direct_transfer_category, can_pick_tickets) VALUES
(1, 'Counter 1', 1, 1, 1, 1, 0, 0, 0, 1),
(2, 'Counter 2', 2, 1, 1, 1, 0, 0, 0, 1)
ON DUPLICATE KEY UPDATE counter_name = VALUES(counter_name), counter_zone = VALUES(counter_zone);

INSERT INTO countercategories (cc_counter, cc_category, cc_enabled) VALUES
(1, 1, 1),
(1, 2, 1),
(2, 1, 1)
ON DUPLICATE KEY UPDATE cc_enabled = VALUES(cc_enabled);

INSERT INTO kiosks (kiosk_id, kiosk_name, kiosk_printer_type, kiosk_printer_location, kiosk_printer_parameters, kiosk_zone, kiosk_updated) VALUES
(1, 'Main Kiosk', 'TCP', '127.0.0.1', '9100', 1, 0)
ON DUPLICATE KEY UPDATE kiosk_name = VALUES(kiosk_name), kiosk_zone = VALUES(kiosk_zone);

INSERT INTO kioskbuttons (kb_kiosk, kb_category, kb_priority) VALUES
(1, 1, 0),
(1, 2, 1)
ON DUPLICATE KEY UPDATE kb_priority = VALUES(kb_priority);

INSERT INTO bigdisplayscounters (bdc_bigdisplay, bdc_counter) VALUES
(1, 1),
(1, 2)
ON DUPLICATE KEY UPDATE bdc_bigdisplay = VALUES(bdc_bigdisplay);

INSERT INTO bigdisplayforcounter (bd_id, counter_id, quantity) VALUES
(1, 1, 5)
ON DUPLICATE KEY UPDATE quantity = VALUES(quantity);

INSERT INTO bigdisplayservices (bd_id, category_id, qty, priority) VALUES
(1, 1, 5, 0),
(1, 2, 5, 1)
ON DUPLICATE KEY UPDATE qty = VALUES(qty), priority = VALUES(priority);

INSERT INTO events (event_id, event_time, event_category, event_no, event_priority, event_level, event_language, event_zone, event_kiosk) VALUES
(1, NOW() - INTERVAL 20 MINUTE, 1, 1, 0, 0, 'ar', 1, 1),
(2, NOW() - INTERVAL 10 MINUTE, 2, 1, 1, 0, 'ar', 1, 1),
(3, NOW() - INTERVAL 5 MINUTE, 1, 2, 0, 1, 'ar', 1, 1)
ON DUPLICATE KEY UPDATE event_time = VALUES(event_time), event_level = VALUES(event_level);

INSERT INTO events_logs (log_type, log_event, log_clerk, log_counter, log_zone, log_time, log_ip_address) VALUES
(2, 3, 1, 1, 1, NOW() - INTERVAL 4 MINUTE, '127.0.0.1');

INSERT INTO displays_logs (log_event, log_counter, log_display, log_zone, log_time) VALUES
(3, 1, 1, 1, NOW() - INTERVAL 4 MINUTE);

INSERT INTO feedback (fb0, fb1, fb2, fb3, fb4, feedback_note, feedback_date) VALUES
(5, 4, 5, 4, 5, 'Demo feedback entry', NOW() - INTERVAL 1 DAY);

INSERT INTO followups (serial_no, client_name, mobile_number, category_id, subcategory_id, clerk_id, notes, date_created, is_done) VALUES
('DEMO-FU-001', 'عميل تجريبي', '0501111111', 1, 1, 1, 'متابعة تجريبية لاختبار التقارير', NOW() - INTERVAL 2 DAY, 0);

INSERT INTO extension_numbers (extension_no, extension_name, extension_desc) VALUES
('101', 'Reception', 'Main reception desk'),
('102', 'Customer Service', 'Customer service department'),
('103', 'Payments', 'Payments department')
ON DUPLICATE KEY UPDATE extension_name = VALUES(extension_name);

-- Additional followups spread across the last 10 days so date-range filters,
-- charts and pagination on the reports/search admin pages have real data
-- (not just the single 2-day-old demo row above) to render out of the box.
INSERT INTO followups (serial_no, day_order_no, client_name, mobile_number, category_id, subcategory_id, extension_no, clerk_id, date_created, date_done, is_done) VALUES
('DEMO-FU-101', 1, 'Demo Client 1', '0501234501', 1, 1, '101', 1, NOW(), NOW() + INTERVAL 1 DAY, 1),
('DEMO-FU-102', 2, 'Demo Client 2', '0501234502', 1, 1, '101', 1, NOW(), NULL, 0),
('DEMO-FU-103', 3, 'Demo Client 3', '0501234503', 2, 2, '102', 1, NOW(), NOW(), 1),
('DEMO-FU-104', 1, 'Demo Client 4', '0501234504', 1, 1, '103', 1, NOW() - INTERVAL 1 DAY, NOW(), 1),
('DEMO-FU-105', 2, 'Demo Client 5', '0501234505', 2, 2, '102', 1, NOW() - INTERVAL 1 DAY, NULL, 0),
('DEMO-FU-106', 1, 'Demo Client 6', '0501234506', 1, 1, '101', 1, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 2 DAY, 1),
('DEMO-FU-107', 2, 'Demo Client 7', '0501234507', 2, 2, '102', 1, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 1 DAY, 1),
('DEMO-FU-108', 1, 'Demo Client 8', '0501234508', 1, 1, '103', 1, NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 4 DAY, 1),
('DEMO-FU-109', 1, 'Demo Client 9', '0501234509', 2, 2, '101', 1, NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 5 DAY, 1),
('DEMO-FU-110', 2, 'Demo Client 10', '0501234510', 1, 1, '102', 1, NOW() - INTERVAL 10 DAY, NULL, 0)
ON DUPLICATE KEY UPDATE client_name = VALUES(client_name);
